### ISSUE TITLE
Feature Request: Do not bust caches for disabled element saves

### ISSUE THREAD

**Issue by rungta** [nystudio107/fastcgicachebust#1]
It would be great to let the cache remain warm when users are working on elements that are disabled (and hence assumed private). Can the plugin be updated to forego busting the cache if the previous as well as new `status` of the element is either `disabled`, `pending` or `expired`.

**Comment by khalwat** [comment]
That's a good suggestion. Also there are a few ElementTypes that I think we should ignore altogether.

**Comment by khalwat** [comment]
Implemented in 1.0.3:

https://github.com/nystudio107/fastcgicachebust/releases/tag/1.0.3

**Comment by rungta** [comment]
Excellent. Thanks!
